# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QApplication, QWidget

from socket_server import recv_reply
from student import student
from course import course
from SQLite import getNameList

class Ui_Form(QWidget):

    cour = course('网络编程', getNameList())

    # def restart_list(self):
    #      # self.cour.singOut = self.cour.singOut+self.cour.signIn
    #     # self.cour.signIn = []

    def turn_off(self):
        os._exit(0)

    def setupUi(self):
        self.resize(762, 730)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(250, 10, 261, 41))
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(self)
        self.radioButton.setGeometry(QtCore.QRect(30, 90, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self)
        self.radioButton_2.setGeometry(QtCore.QRect(180, 90, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self)
        self.radioButton_3.setGeometry(QtCore.QRect(320, 90, 115, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self)
        self.radioButton_4.setGeometry(QtCore.QRect(610, 90, 115, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self)
        self.radioButton_5.setGeometry(QtCore.QRect(470, 90, 115, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.sign_in = QtWidgets.QLabel(self)
        self.sign_in.setGeometry(QtCore.QRect(30, 190, 531, 241))
        self.sign_in.setObjectName("sign_in")
        self.sign_in.setFrameShape(QtWidgets.QFrame.Box)
        self.sign_in.setStyleSheet('background-color: rgb(255, 255, 255)')
        self.sign_in.setLineWidth(1)
        self.sign_out = QtWidgets.QLabel(self)
        self.sign_out.setGeometry(QtCore.QRect(30, 470, 531, 241))
        self.sign_out.setObjectName("sign_out")
        self.sign_out.setFrameShape(QtWidgets.QFrame.Box)
        self.sign_out.setStyleSheet('background-color: rgb(255, 255, 255)')
        self.sign_out.setLineWidth(1)
        self.course_connect_status = QtWidgets.QLabel(self)
        self.course_connect_status.setGeometry(QtCore.QRect(30, 130, 651, 31))
        self.course_connect_status.setObjectName("course_connect_status")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(610, 380, 93, 28))
        self.pushButton.setObjectName("pushButton")
        # self.pushButton.clicked.connect(self.restart_list)
        self.time = QtWidgets.QLabel(self)
        self.time.setGeometry(QtCore.QRect(30, 50, 651, 31))
        self.time.setObjectName("time")

        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 560, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 470, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton.clicked.connect(self.turn_off)
        self.setWindowTitle('人脸考勤系统服务器 v1.0')
        self.retranslateUi()
        self.show()



    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "人脸考勤系统服务器 v1.0"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:15pt; font-weight:600;\">智慧教室人脸考勤系统    </span></p></body></html>"))
        self.radioButton.setText(_translate("Form", "南湖一教一阶"))
        self.radioButton_2.setText(_translate("Form", "南湖一教二阶"))
        self.radioButton_3.setText(_translate("Form", "南湖一教六阶"))
        self.radioButton_4.setText(_translate("Form", "南湖三教103"))
        self.radioButton_5.setText(_translate("Form", "南湖一教327"))
        self.sign_in.setText(_translate("Form", "已签到列表"))
        self.sign_out.setText(_translate("Form", "未签到列表"))
        self.course_connect_status.setText(_translate("Form", "未连接客户端......"))
        self.pushButton.setText(_translate("Form", "签到复位"))
        self.time.setText(
            time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + '                                  当前课程：网络编程')
        self.time.setFont(QFont("微软雅黑", 10, QFont.Bold))
        self.pushButton_2.setText(_translate("Form", "退出系统"))
        self.pushButton_3.setText(_translate("Form", "课程列表"))

    def execute(self):
        recv_reply(self, self.cour)
    def timeinfo(self):
        self.time.setText(
            time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + '                               当前课程：网络编程')
        self.time.setFont(QFont("微软雅黑", 10, QFont.Bold))


if __name__=="__main__":
    app=QtWidgets.QApplication(sys.argv)
    ui=Ui_Form()
    ui.setupUi()
    ui.timer = QTimer()
    ui.timer.start(500)
    ui.timer.timeout.connect(ui.timeinfo)
    ui.timer.timeout.connect(ui.execute)

    sys.exit(app.exec_())
